### ISSUE TITLE
Create the simulation window

### ISSUE THREAD

**Issue by petrolifero** [teixeira-pedro/trabalhoAvaliacaoDesempenho#1]
When the first window show up, and we select the nodejs code, choose number of clients and rate of clients, we can click on button and open another window, that will show the simulation state over time

**Comment by teixeira-pedro** [comment]
Perfeito! Ficam claros, o código sob teste, e os parametros de taxa e qtd e clientes, e depois, também fica bem evidente o comparativo da simulação. Concluído!
Perfect! Its evidentializes with accuracy, the code under test, with the client-rate/client-amount , and the comparative of simulation . It's done!
